apiVersion: v1
kind: Service
metadata:
  namespace: REPLACE_NAMESPACE
  name: agentinstalladmission
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: agentinstalladmission-serving-cert
spec:
  selector:
    app: agentinstalladmission
  ports:
  - port: 443
    targetPort: 9443
    protocol: TCP
